"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClientProvider, QueryClient } from "react-query";
import { Provider } from "react-redux";
import { store } from "../redux/store";

import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });
const client = new QueryClient();

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={client}>
          <Provider store={store}>{children}</Provider>
        </QueryClientProvider>
        <div id="portal"></div>
      </body>
    </html>
  );
}
